- menu_name: "Saiba mais"

- name: "Desenvolvemos seu projeto"
  url: "http://inspiradanacomputacao.github.io"
  class: "rss-link"
  title: "Subscribe to RSS"

- name: "Palestras e aulas particulares"
  url: "http://inspiradanacomputacao.github.io"
  class: "sitemap-link"
  title: "Sitemap for Google Webmastertools"

- name: "Contato"
  url: "/contact/"
  class: "services-contact"
  title: "Contato"