- menu_name: "Saiba mais"

- name: "Desenvolvemos seu projeto"
  url: "http://inspiradanacomputacao.github.io"
  class: "rss-link"
  title: "Subscribe to RSS"

- name: "Parcerias"
  url: "http://inspiradanacomputacao.github.io"
  class: "sitemap-link"
  title: "Parceria InspirAda"

- name: "Contato"
  url: "/contato/"
  class: "services-contact"
  title: "Fale Conosco"